name: Release npm package

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@v1

        - name: Run ci
          run: npm ci
        - name: Run build
          run: npm run build --if-present
        - name: Run semantic release
          run: npx semantic-release --branches main

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}